import Head from "next/head";
import { Inter } from "@next/font/google";
// icon imports
import { BsFillMoonStarsFill, BsLinkedin, BsSunFill } from "react-icons/bs";
import { FaTwitterSquare, FaGithubSquare } from "react-icons/fa";
import { MdEmail } from "react-icons/md";
import Image from "next/image";
//image imports
import me from "../public/me.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import web7 from "../public/web7.png";
// hooks import
import { useState, useEffect } from "react";
const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  useEffect(() => {
    if (localStorage.getItem("isDarkMode") === null) {
      localStorage.setItem("isDarkMode", JSON.stringify(darkMode));
    } else {
      let isDarkMode = localStorage.getItem("isDarkMode");
      setDarkMode(JSON.parse(isDarkMode));
    }
    console.log(darkMode);
  }, []);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Aneroos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./icon.png" />
      </Head>
      <style>
        {" "}
        @import
        url('https://fonts.googleapis.com/css2?family=Libre+Baskerville&family=Poppins:wght@300&display=swap');{" "}
      </style>
      <main className="bg-white text-black px-10 md:px-20 lg:px-40 pb-12 dark:text-white dark:bg-gray-900 ">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">Aneroos</h1>
            <ul className="flex justify-between">
              <li
                onClick={() => {
                  localStorage.setItem("isDarkMode", JSON.stringify(!darkMode));
                  setDarkMode((prev) => !prev);
                  console.log(darkMode);
                }}
              >
                {darkMode ? (
                  <BsSunFill className="cursor-pointer text-xl" />
                ) : (
                  <BsFillMoonStarsFill className="cursor-pointer text-xl " />
                )}
              </li>
              <li>
                <a
                  target={"_blank"}
                  href="https://mstorage.jobinjacdn.com/records/files/uploads/documents/85ac5aef-f78a-4d30-92fd-35364e015456.pdf?requester=35312e37392e3136312e323339&resource=753a32353435323132&from=6170706c69636174696f6e5f666f726d&X-Amz-Content-Sha256=e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=oetSom924MQvtCRu9N6vvQ4bt8cG9HSpRnxWU756SyWy5NVt6nTpmfA9aV2b%2F20221227%2F%2Fs3%2Faws4_request&X-Amz-Date=20221227T002827Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1800&X-Amz-Signature=a818a9ad1fbaf3de116e22b5200ca15f64cf818e1e961f95e87b509f09f1e4d8"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mr-4"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-4xl py-2 text-teal-600 font-medium md:text-6xl">
              Sourena Ganji
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl">React Developer</h3>
            <p className="text-md py-5 leading-8 text-gray-700 md:text-xl max-w-xl mx-auto dark:text-gray-400 ">
              {" "}
              This is Sourena Ganji , a React Developer. I've made this website
              for you to introduce myself better :) . Let's start this journey{" "}
            </p>
          </div>
          <div className="text-5xl flex items-center justify-center gap-16 text-gray-600 dark:text-gray-400 ">
            <a
              href="https://www.linkedin.com/in/sourena-ganji/"
              target={"_blank"}
              className="hover:text-black dark:hover:text-white"
            >
              <BsLinkedin />
            </a>
            <a
              href="https://github.com/soorenaganji?tab=repositories"
              target={"_blank"}
              className="hover:text-black dark:hover:text-white"
            >
              <FaGithubSquare />
            </a>
            <a
              href="https://sorena.ganji83@gmail.com"
              target={"_blank"}
              className="hover:text-black dark:hover:text-white"
            >
              <MdEmail />
            </a>
          </div>
          <div className="relative bg-gradient-to-b from-teal-500 mx-auto h-80 w-80 rounded-full mt-10 overflow-hidden mb-8 md:h-96 md:w-96">
            <Image src={me} layout="fill" objectFit="cover" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1">Services I Offer</h3>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-400 ">
              As you know , I'm a front-end developer and I'm expert in
              <span className="text-teal-500"> Building the UI</span>.
            </p>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-400">
              And my Job is to make
              <span className="text-teal-500">
                {" "}
                Fast and User Friendly
              </span>{" "}
              Websites. and at the same time , write{" "}
              <span className="text-teal-500">Developer Friendly</span> and
              <span className="text-teal-500"> Reusable Components</span>
            </p>
          </div>
          <div className="lg:flex lg:gap-10">
            <div className="text-center shadow-lg p-10 rounded-lg my-10 dark:bg-white">
              <Image
                src={design}
                width="100"
                height={"100"}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-black">
                Beautiful Websites
              </h3>
              <p className="py-2 dark:text-black">
                UI designers are my best friends and it's my pleasure to
                cooperate with them to make a beautiful website :)
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1  ">Tailwind</p>
              <p className="text-gray-800 py-1  ">module css</p>
              <p className="text-gray-800 py-1  ">React Icons</p>
              <p className="text-gray-800 py-1  ">Google Font API</p>
            </div>

            <div className="text-center shadow-xl p-10 rounded-lg my-10 dark:bg-white">
              <Image
                src={code}
                width="100"
                height={"100"}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-black">
                Optimized Codes
              </h3>
              <p className="py-2 dark:text-black">
                I'll do my best to make your website , the fastest in my own
                field. Which affects the UX and improves the SEO
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1  ">React.js</p>
              <p className="text-gray-800 py-1  ">Next.js</p>
              <p className="text-gray-800 py-1  ">SPA</p>
              <p className="text-gray-800 py-1  ">Redux</p>
            </div>
            <div className="text-center shadow-xl p-10 rounded-lg my-10 dark:bg-white">
              <Image
                src={consulting}
                width="100"
                height={"100"}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 dark:text-black">
                Fully Customized
              </h3>
              <p className="py-2 dark:text-black">
                I want all my clients to be happy and satisfied. Which makes me
                , be agile and interact with my clients all the time
              </p>
              <h4 className="py-4 text-teal-600">Methods I Use</h4>
              <p className="text-gray-800 py-1  ">Agile</p>
              <p className="text-gray-800 py-1  ">Scrum</p>
            </div>
          </div>
        </section>
        <section>
          <div className="mb-1">
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-400 ">
              These are a number of my projects which I made with
              <span className="text-teal-500">React</span>.
            </p>
            <p className="text-md py-2 leading-8 text-gray-700 dark:text-gray-400 ">
              It's just photos of them , but you can see all them
              <span className="text-teal-500"> Online </span> with the{" "}
              <span className="text-teal-500">Source Code </span>
              with some description on my{" "}
              <span className="text-teal-500">Resume</span>
            </p>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
              <div className="basis-1/3 flex-1">
                <Image
                  src={web1}
                  className="rounded-lg object-cover w-[100%] h-[100%]"
                />
              </div>

              <div className="basis-1/3 flex-1">
                <Image
                  src={web2}
                  className="rounded-lg object-cover w-[100%] h-[100%]"
                />
              </div>

              <div className="basis-1/3 flex-1">
                <Image
                  src={web3}
                  className="rounded-lg object-cover w-[100%] h-[100%]"
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web4}
                  className="rounded-lg object-cover w-[100%] h-[100%]"
                />
              </div>

              <div className="basis-1/3 flex-1">
                <Image
                  src={web5}
                  className="rounded-lg object-cover w-[100%] h-[100%]"
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web7}
                  className="rounded-lg object-cover w-[100%] h-[100%]"
                />
              </div>
              <div className="basis-1/3 flex-1">
                <Image
                  src={web6}
                  className="rounded-lg object-cover w-[100%] h-[100%]"
                />
              </div>
            </div>
          </div>
        </section>
      </main>
      <div className="py-4 mt-[-4px] bg-gradient-to-r from-cyan-500 to-teal-500 m-auto">
        <p className="text-center text-black">Made With ❤️ By Sourena Ganji </p>
      </div>
    </div>
  );
}
